{
'name': 'CampOS Transportation Application',
'description': 'Manage your bus rides.',
'author': 'Doobi & Darum',
'depends': ['mail','campos_preregistration','campos_final_registration','campos_event','campos_jobber_final'],
'application': True,
'data': ['views/webtourrequestlogger_view.xml',
         'views/webtourusdestination_view.xml',
         #'views/webtourregistration_view.xml',
         'views/webtourusneed_view.xml',  
         'views/webtourconfig_view.xml',   
         'views/webtourfinalregistration_view.xml',
         'views/webtourparticipantoverview_view.xml',
         'views/webtourregistrationoverview_view.xml', 
         'views/webtourmailtemplates.xml', 
         'views/webtour_template.xml',
         'views/webtourdeparture_view.xml',                                                
         'data/webtourusdestination_scheduler.xml',
         'data/webtourusneed_scheduler.xml',
         'data/webtour_config_parameter.xml',
         'security/ir.model.access.csv',
         ],
}