{
'name': 'CampOS Transportation Application',
'description': 'Manage your bus rides.',
'author': 'Doobi & Darum',
'depends': ['mail','campos_preregistration','campos_final_registration','campos_event'],
'application': True,
'data': [#'views/webtourparticipant_view.xml',
         'views/webtourusdestination_view.xml',
         #'views/webtourregistration_view.xml',
         'views/webtourusneed_view.xml',  
         'views/webtourconfig_view.xml',   
         'views/webtourfinalregistration_view.xml',                                            
         'data/webtourusdestination_scheduler.xml',
         'data/webtourusneed_scheduler.xml',
         'data/webtour_config_parameter.xml',
         'security/ir.model.access.csv',
         ],
}